/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_pollaknet_api_facile_pdb_dia_NativePdbReader */

#ifndef _Included_at_pollaknet_api_facile_pdb_dia_NativePdbReader
#define _Included_at_pollaknet_api_facile_pdb_dia_NativePdbReader
#ifdef __cplusplus
extern "C" {
#endif
#undef at_pollaknet_api_facile_pdb_dia_NativePdbReader_ENABLE_DEBUG
#define at_pollaknet_api_facile_pdb_dia_NativePdbReader_ENABLE_DEBUG 0L
#undef at_pollaknet_api_facile_pdb_dia_NativePdbReader_SUCCESS
#define at_pollaknet_api_facile_pdb_dia_NativePdbReader_SUCCESS 0L
#undef at_pollaknet_api_facile_pdb_dia_NativePdbReader_ERROR_COM_INIT_FAILED
#define at_pollaknet_api_facile_pdb_dia_NativePdbReader_ERROR_COM_INIT_FAILED -1L
#undef at_pollaknet_api_facile_pdb_dia_NativePdbReader_ERROR_DIA_INIT_FAILED
#define at_pollaknet_api_facile_pdb_dia_NativePdbReader_ERROR_DIA_INIT_FAILED -2L
#undef at_pollaknet_api_facile_pdb_dia_NativePdbReader_ERROR_OUT_OF_MEMORY
#define at_pollaknet_api_facile_pdb_dia_NativePdbReader_ERROR_OUT_OF_MEMORY -3L
#undef at_pollaknet_api_facile_pdb_dia_NativePdbReader_ERROR_PDB_NOT_FOUND
#define at_pollaknet_api_facile_pdb_dia_NativePdbReader_ERROR_PDB_NOT_FOUND -4L
#undef at_pollaknet_api_facile_pdb_dia_NativePdbReader_ERROR_DIA_SESSION_FAILED
#define at_pollaknet_api_facile_pdb_dia_NativePdbReader_ERROR_DIA_SESSION_FAILED -5L
#undef at_pollaknet_api_facile_pdb_dia_NativePdbReader_ERROR_NO_GLOBAL_SCOPE_FOUND
#define at_pollaknet_api_facile_pdb_dia_NativePdbReader_ERROR_NO_GLOBAL_SCOPE_FOUND -6L
#undef at_pollaknet_api_facile_pdb_dia_NativePdbReader_ERROR_FIELD_NOT_FOUND
#define at_pollaknet_api_facile_pdb_dia_NativePdbReader_ERROR_FIELD_NOT_FOUND -7L
/*
 * Class:     at_pollaknet_api_facile_pdb_dia_NativePdbReader
 * Method:    openPdb
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_pollaknet_api_facile_pdb_dia_NativePdbReader_openPdb
  (JNIEnv *, jobject, jstring);

/*
 * Class:     at_pollaknet_api_facile_pdb_dia_NativePdbReader
 * Method:    getLineNumbersByRVA
 * Signature: (J)Lat/pollaknet/api/facile/pdb/DebugInformation;
 */
JNIEXPORT jobject JNICALL Java_at_pollaknet_api_facile_pdb_dia_NativePdbReader_getLineNumbersByRVA
  (JNIEnv *, jobject, jlong);

/*
 * Class:     at_pollaknet_api_facile_pdb_dia_NativePdbReader
 * Method:    closePdb
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_at_pollaknet_api_facile_pdb_dia_NativePdbReader_closePdb
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
