
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mainFrame */
 
#ifndef _Included_JavaDIA

	#define _Included_JavaDIA
	
	#ifdef __cplusplus
		extern "C" {
	#endif // __cplusplus

	/*
	 * Class:     PdbReader
	 * Package:	  at.pollaknet.api.facile.dia
	 * Method:    openPdb
	 */
	JNIEXPORT jint JNICALL Java_at_pollaknet_api_facile_dia_PdbReader_openPdb(JNIEnv *env, jobject obj, jstring jsPdbPath);

	/*
	* Class:     PdbReader
	* Package:	 facile.dia
	* Method:    getLineNumbersViaRva
	*/
	JNIEXPORT jobject JNICALL Java_at_pollaknet_api_facile_dia_PdbReader_getLineNumbersByRVA(JNIEnv *env, jobject obj, jlong jlRVA);

	/*
	* Class:     PdbReader
	* Package:	 facile.dia
	* Method:    closePdb
	*/
	JNIEXPORT void JNICALL Java_at_pollaknet_api_facile_dia_PdbReader_closePdb(JNIEnv *env, jobject obj);

	#ifdef __cplusplus
		}
	#endif //__cplusplus

#endif // _Included_JavaDIA
